// <auto-generated />
using System;
using ApiCognosV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCognosV1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240221041301_contacto_eme")]
    partial class contacto_eme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCognosV1.Modelos.AnalisisFU", b =>
                {
                    b.Property<int>("analisis_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("analisis_id"));

                    b.Property<string>("analisis_ant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("analisis_ant_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("analisis_con")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("analisis_con_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("analisis_cons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("analisis_cons_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("analisis_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("analisis_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("analisis_paciente_id")
                        .HasColumnType("int");

                    b.HasKey("analisis_id");

                    b.HasIndex("analisis_paciente_id");

                    b.ToTable("AnalisisFU");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Comentarios", b =>
                {
                    b.Property<int>("com_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("com_id"));

                    b.Property<string>("com_comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("com_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<int>("com_index")
                        .HasColumnType("int");

                    b.Property<string>("com_nombre_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("com_paciente_id")
                        .HasColumnType("int");

                    b.Property<int>("com_usuario_id")
                        .HasColumnType("int");

                    b.HasKey("com_id");

                    b.HasIndex("com_paciente_id");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ConsultaM", b =>
                {
                    b.Property<int>("con_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("con_id"));

                    b.Property<DateTime>("con_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("con_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("con_motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("con_paciente_id")
                        .HasColumnType("int");

                    b.HasKey("con_id");

                    b.HasIndex("con_paciente_id");

                    b.ToTable("ConsultaM");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ConsumoSust", b =>
                {
                    b.Property<int>("consumo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("consumo_id"));

                    b.Property<string>("consumo_cantidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumo_edad_inicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("consumo_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("consumo_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("consumo_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("consumo_sino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumo_sustancia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumo_tiempo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("consumo_id");

                    b.HasIndex("consumo_paciente_id");

                    b.ToTable("ConsumoSust");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Creencias", b =>
                {
                    b.Property<int>("creencia_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("creencia_id"));

                    b.Property<DateTime>("creencia_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("creencia_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("creencia_irra1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creencia_irra9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("creencia_paciente_id")
                        .HasColumnType("int");

                    b.HasKey("creencia_id");

                    b.HasIndex("creencia_paciente_id");

                    b.ToTable("Creencias");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.DiagnosticoDS", b =>
                {
                    b.Property<int>("diag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("diag_id"));

                    b.Property<string>("diag_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("diag_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("diag_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("diag_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("diag_titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("diag_id");

                    b.HasIndex("diag_paciente_id");

                    b.ToTable("DiagnosticoDS");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Edocivil", b =>
                {
                    b.Property<int>("civil_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("civil_id"));

                    b.Property<string>("civil_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("civil_id");

                    b.ToTable("Edocivil");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Escolaridad", b =>
                {
                    b.Property<int>("esc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("esc_id"));

                    b.Property<string>("esc_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("esc_id");

                    b.ToTable("Escolaridad");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.EvolucionPR", b =>
                {
                    b.Property<int>("evo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("evo_id"));

                    b.Property<string>("evo_curso_problema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evo_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("evo_factores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("evo_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("evo_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("evo_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("evo_titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("evo_id");

                    b.HasIndex("evo_paciente_id");

                    b.ToTable("EvolucionPR");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Files", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DataFiles")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("files_paciente_id")
                        .HasColumnType("int");

                    b.Property<int>("files_tipo_prueba")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("files_paciente_id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.FormCaso", b =>
                {
                    b.Property<int>("form_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("form_id"));

                    b.Property<string>("form_contraste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("form_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("form_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("form_hipotesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("form_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("form_titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("form_id");

                    b.HasIndex("form_paciente_id");

                    b.ToTable("FormCaso");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Genero", b =>
                {
                    b.Property<int>("gen_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gen_id"));

                    b.Property<string>("gen_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gen_id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Informe", b =>
                {
                    b.Property<int>("inf_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inf_id"));

                    b.Property<int?>("inf_coterapeuta")
                        .HasColumnType("int");

                    b.Property<string>("inf_domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inf_edad")
                        .HasColumnType("int");

                    b.Property<int>("inf_edocivil")
                        .HasColumnType("int");

                    b.Property<string>("inf_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inf_escolaridad")
                        .HasColumnType("int");

                    b.Property<string>("inf_estructura_fam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("inf_fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("inf_fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("inf_genero")
                        .HasColumnType("int");

                    b.Property<string>("inf_materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inf_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inf_ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inf_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("inf_paterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inf_telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("inf_terapeuta")
                        .HasColumnType("int");

                    b.Property<int?>("inf_tutor")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("inf_ultimo_mov")
                        .HasColumnType("datetime2");

                    b.HasKey("inf_id");

                    b.HasIndex("inf_paciente_id");

                    b.ToTable("Informe");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.LineaVida", b =>
                {
                    b.Property<int>("lin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lin_id"));

                    b.Property<string>("lin_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lin_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("lin_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("lin_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("lin_titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lin_id");

                    b.HasIndex("lin_paciente_id");

                    b.ToTable("LineaVida");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Maestro_pruebas", b =>
                {
                    b.Property<int>("maestro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maestro_id"));

                    b.Property<DateTime>("maestro_fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("maestro_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("maestro_tipo_prueba")
                        .HasColumnType("int");

                    b.HasKey("maestro_id");

                    b.ToTable("Maestro_pruebas");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.OtrasAR", b =>
                {
                    b.Property<int>("otras_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("otras_id"));

                    b.Property<string>("otras_apoyo_s")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otras_aspectos_m")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otras_autocontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otras_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("otras_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("otras_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("otras_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("otras_recursos_p")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otras_situacion_v")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otras_titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("otras_id");

                    b.HasIndex("otras_paciente_id");

                    b.ToTable("OtrasAR");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Pacientes", b =>
                {
                    b.Property<int>("pac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pac_id"));

                    b.Property<int?>("pac_comparte_usrid")
                        .HasColumnType("int");

                    b.Property<string>("pac_contacto_eme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pac_coterapeuta")
                        .HasColumnType("int");

                    b.Property<string>("pac_domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pac_edad")
                        .HasColumnType("int");

                    b.Property<int>("pac_edocivil")
                        .HasColumnType("int");

                    b.Property<string>("pac_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pac_escolaridad")
                        .HasColumnType("int");

                    b.Property<string>("pac_especifique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_estructura_fam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pac_fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("pac_fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("pac_genero")
                        .HasColumnType("int");

                    b.Property<string>("pac_materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_paterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pac_telefono_eme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pac_terapeuta")
                        .HasColumnType("int");

                    b.Property<int?>("pac_tutor")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("pac_usr_id")
                        .HasColumnType("int");

                    b.HasKey("pac_id");

                    b.HasIndex("pac_usr_id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Perfiles", b =>
                {
                    b.Property<int>("per_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("per_id"));

                    b.Property<string>("per_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("per_id");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.PrevioSalud", b =>
                {
                    b.Property<int>("previo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("previo_id"));

                    b.Property<DateTime>("previo_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("previo_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("previo_medicamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("previo_medico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("previo_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("previo_problema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("previo_tiempo_psicologico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("previo_tiempo_tratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("previo_id");

                    b.HasIndex("previo_paciente_id");

                    b.ToTable("PrevioSalud");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ProbObj", b =>
                {
                    b.Property<int>("pro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pro_id"));

                    b.Property<DateTime>("pro_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("pro_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("pro_objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pro_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("pro_problema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pro_tecnica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pro_id");

                    b.HasIndex("pro_paciente_id");

                    b.ToTable("ProbObj");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ProblemasMed", b =>
                {
                    b.Property<int>("problema_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("problema_id"));

                    b.Property<DateTime>("problema_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("problema_fecha_ini_trata")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("problema_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("problema_medicamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("problema_medico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("problema_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("problema_problema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("problema_tiempo_tratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("problema_id");

                    b.HasIndex("problema_paciente_id");

                    b.ToTable("ProblemasMed");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespBAIan", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespBAIan");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespBDIdp", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<string>("res_respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("res_id");

                    b.ToTable("RespBDIdp");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespEllis", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespEllis");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespIsraC", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta1")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta2")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta3")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta4")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta5")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta6")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta7")
                        .HasColumnType("int");

                    b.Property<int>("res_sum")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespIsraC");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespIsraF", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta1")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta10")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta2")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta3")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta4")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta5")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta6")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta7")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta8")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta9")
                        .HasColumnType("int");

                    b.Property<int>("res_sum")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespIsraF");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespIsraM", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta1")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta2")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta3")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta4")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta5")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta6")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta7")
                        .HasColumnType("int");

                    b.Property<int>("res_sum")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespIsraM");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespSCID", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespSCID");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.RespSCL", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("res_id"));

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.HasKey("res_id");

                    b.ToTable("RespSCL");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.SaludFM", b =>
                {
                    b.Property<int>("salud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("salud_id"));

                    b.Property<string>("salud_act_fisica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salud_act_fisica_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salud_alimentacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salud_alimentacion_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("salud_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("salud_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("salud_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("salud_sueno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salud_sueno_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("salud_id");

                    b.HasIndex("salud_paciente_id");

                    b.ToTable("SaludFM");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Sesion", b =>
                {
                    b.Property<int>("sesion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sesion_id"));

                    b.Property<string>("sesion_abc_tareas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_caso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_consecuencia_emo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_coterapeuta")
                        .HasColumnType("int");

                    b.Property<string>("sesion_evento_act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sesion_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("sesion_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("sesion_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_notas_ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_obj_cond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_obj_emo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_obj_prac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_objetivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_otras_tecnicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("sesion_pensamientos_cre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_preguntas_debate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_recomendacion_sup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_rev_tarea")
                        .HasColumnType("int");

                    b.Property<string>("sesion_tarea_asignada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_tecnica_abc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_tecnicas_estrategias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_terapeuta")
                        .HasColumnType("int");

                    b.HasKey("sesion_id");

                    b.HasIndex("sesion_paciente_id");

                    b.ToTable("Sesion");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TablaPrueba", b =>
                {
                    b.Property<int>("prueba_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prueba_id"));

                    b.Property<string>("prueba_descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("prueba_id");

                    b.ToTable("TablaPrueba");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestBAI_Inv_An", b =>
                {
                    b.Property<int>("bai_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bai_id"));

                    b.Property<string>("bai_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bai_id");

                    b.ToTable("TestBAI_Inv_An");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestBDI_Inv_Dp", b =>
                {
                    b.Property<int>("bdi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bdi_id"));

                    b.Property<string>("bdi_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bdi_id");

                    b.ToTable("TestBDI_Inv_Dp");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestEllis", b =>
                {
                    b.Property<int>("ellis_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ellis_id"));

                    b.Property<string>("ellis_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ellis_p")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ellis_id");

                    b.ToTable("TestEllis");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestIsraC", b =>
                {
                    b.Property<int>("isra_c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("isra_c_id"));

                    b.Property<string>("isra_c_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("isra_c_id");

                    b.ToTable("TestIsraC");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestIsraF", b =>
                {
                    b.Property<int>("isra_f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("isra_f_id"));

                    b.Property<string>("isra_f_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("isra_f_id");

                    b.ToTable("TestIsraF");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestIsraM", b =>
                {
                    b.Property<int>("isra_m_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("isra_m_id"));

                    b.Property<string>("isra_m_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("isra_m_id");

                    b.ToTable("TestIsraM");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestSCID", b =>
                {
                    b.Property<int>("scid_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("scid_id"));

                    b.Property<string>("scid_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("scid_id");

                    b.ToTable("TestSCID");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.TestSCL", b =>
                {
                    b.Property<int>("scl_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("scl_id"));

                    b.Property<string>("scl_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("scl_id");

                    b.ToTable("TestSCL");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Tratamiento", b =>
                {
                    b.Property<int>("trata_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("trata_id"));

                    b.Property<DateTime>("trata_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("trata_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("trata_objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trata_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("trata_tecnica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("trata_id");

                    b.HasIndex("trata_paciente_id");

                    b.ToTable("Tratamiento");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Usuarios", b =>
                {
                    b.Property<int>("usr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usr_id"));

                    b.Property<string>("usr_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("usr_fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("usr_materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usr_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usr_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usr_paterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usr_per_id")
                        .HasColumnType("int");

                    b.HasKey("usr_id");

                    b.HasIndex("usr_per_id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.cat_terapeutas", b =>
                {
                    b.Property<int>("tera_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tera_id"));

                    b.Property<string>("tera_materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tera_nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tera_paterno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tera_id");

                    b.ToTable("cat_terapeutas");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_baian_x", b =>
                {
                    b.Property<string>("bai_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("Vista_BAIAN", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_bdidp_x", b =>
                {
                    b.Property<string>("bdi_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("Vista_BDIDP", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_ellis_x", b =>
                {
                    b.Property<string>("ellis_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ellis_id")
                        .HasColumnType("int");

                    b.Property<string>("ellis_p")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("Vista_Ellis", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_informe_x", b =>
                {
                    b.Property<string>("civil_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esc_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gen_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("inf_coterapeuta")
                        .HasColumnType("int");

                    b.Property<string>("inf_domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inf_edad")
                        .HasColumnType("int");

                    b.Property<int>("inf_edocivil")
                        .HasColumnType("int");

                    b.Property<string>("inf_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inf_escolaridad")
                        .HasColumnType("int");

                    b.Property<string>("inf_estructura_fam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("inf_fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("inf_fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("inf_genero")
                        .HasColumnType("int");

                    b.Property<int>("inf_id")
                        .HasColumnType("int");

                    b.Property<string>("inf_materno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inf_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inf_ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("inf_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("inf_paterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inf_telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("inf_terapeuta")
                        .HasColumnType("int");

                    b.Property<int?>("inf_tutor")
                        .HasColumnType("int");

                    b.Property<DateTime>("inf_ultimo_mov")
                        .HasColumnType("datetime2");

                    b.Property<string>("supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("Vista_Informe", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_israC_x", b =>
                {
                    b.Property<string>("isra_c_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_respuesta1")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta2")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta3")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta4")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta5")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta6")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta7")
                        .HasColumnType("int");

                    b.Property<int>("res_sum")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VistaIsraC", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_israF_x", b =>
                {
                    b.Property<string>("isra_f_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_respuesta1")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta10")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta2")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta3")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta4")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta5")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta6")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta7")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta8")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta9")
                        .HasColumnType("int");

                    b.Property<int>("res_sum")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VistaIsraF", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_israM_x", b =>
                {
                    b.Property<string>("isra_m_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<string>("res_observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("res_respuesta1")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta2")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta3")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta4")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta5")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta6")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta7")
                        .HasColumnType("int");

                    b.Property<int>("res_sum")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VistaIsraM", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_scid_x", b =>
                {
                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.Property<string>("scid_desc")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("Vista_SCID", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_scl_x", b =>
                {
                    b.Property<int>("res_id_maestro")
                        .HasColumnType("int");

                    b.Property<int>("res_id_paciente")
                        .HasColumnType("int");

                    b.Property<int>("res_respuesta")
                        .HasColumnType("int");

                    b.Property<string>("scl_desc")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("Vista_SCL", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.v_sesion_x", b =>
                {
                    b.Property<string>("coterapeuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rev_tarea_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_abc_tareas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_caso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_consecuencia_emo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_coterapeuta")
                        .HasColumnType("int");

                    b.Property<string>("sesion_evento_act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sesion_fecha_captura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("sesion_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("sesion_id")
                        .HasColumnType("int");

                    b.Property<string>("sesion_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_notas_ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_obj_cond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_obj_emo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_obj_prac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_objetivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_otras_tecnicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("sesion_pensamientos_cre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_preguntas_debate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_recomendacion_sup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_rev_tarea")
                        .HasColumnType("int");

                    b.Property<string>("sesion_tarea_asignada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_tecnica_abc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sesion_tecnicas_estrategias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sesion_terapeuta")
                        .HasColumnType("int");

                    b.Property<string>("terapeuta")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("v_sesiones", (string)null);
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.AnalisisFU", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("analisis_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Comentarios", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("com_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ConsultaM", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("con_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ConsumoSust", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("consumo_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Creencias", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("creencia_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.DiagnosticoDS", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("diag_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.EvolucionPR", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("evo_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Files", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("files_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.FormCaso", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("form_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Informe", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("inf_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.LineaVida", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("lin_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.OtrasAR", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("otras_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Pacientes", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("pac_usr_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.PrevioSalud", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("previo_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ProbObj", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("pro_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.ProblemasMed", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("problema_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.SaludFM", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("salud_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Sesion", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("sesion_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Tratamiento", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Pacientes", "Pacientes")
                        .WithMany()
                        .HasForeignKey("trata_paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiCognosV1.Modelos.Usuarios", b =>
                {
                    b.HasOne("ApiCognosV1.Modelos.Perfiles", "Perfiles")
                        .WithMany()
                        .HasForeignKey("usr_per_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
